# Generated by Django 3.0.4 on 2020-03-12 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_auto_20200312_1205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='LoginCredentials',
            new_name='LoginCredential',
        ),
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
