# Generated by Django 3.0.4 on 2020-03-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_auto_20200312_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventPoster',
            field=models.ImageField(upload_to=''),
        ),
    ]
