# Generated by Django 3.0.4 on 2020-03-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0005_remove_event_eventposter'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registrationEndDateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registrationStartDateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
