# Generated by Django 3.0.4 on 2020-03-12 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0007_event_isdeleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventDate',
            field=models.DateField(default=datetime.datetime(2020, 3, 12, 16, 11, 27, 476478)),
        ),
    ]
